name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Comando de rescate para saltar el fallo de repositorios caídos de Linux
      - name: Fix APT Repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo apt-get update

      # Usamos la acción estable certificada v1
      - name: Build APK with Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          repository_root: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-Android
          path: bin/*.apk
