name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 zip unzip openjdk-17-jdk lld
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv

      - name: Build with Buildozer
        run: yes | buildozer -v android debug
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-Android
          path: bin/*.apk
