name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Usamos el contenedor oficial corregido de ArtemSBulgakov
      - name: Build APK with Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v3
        with:
          command: buildozer -v android debug
          repository_root: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-Android
          path: bin/*.apk
